### ISSUE TITLE
Feature: Add optional file path for reading API key

### ISSUE THREAD

**Issue by TornaxO7** [eeeXun/gtt#29]
Hello!
My dotfiles are public and hence I can't really insert my API key for `deepl` into my config and push it to github... could you please add an option to enter a file path instead where the password can be read from?
For example:

```yaml
api_key:
  chatgpt:
     value: api-key-to-chatgpt # <- Replace with your API Key
  deepl:
     file_path: /home/tornax/secrets/gtt/deepl.txt
```
so either `value` or `file_path` can be used to provide the api key
