### ISSUE TITLE
Deepl: Can't read from API key, although it's added

### ISSUE THREAD

**Issue by TornaxO7** [eeeXun/gtt#30]
Hi!
I have the following file (for testing):
`~/.config/gtt/server.yaml`
```yaml
api_key:
  deepl:
    value: abcde-fghij-lol
```
But I'm getting the following error message:

![image](https://github.com/eeeXun/gtt/assets/50843046/672a550c-1280-4531-a1e8-786b8b124df1)

I've also tried it with the following config file:
`~/.config/gtt/server.yaml`
```yaml
api_key:
  deepl:
    value: "abcde-fghij-lol"
```

Also using
`~/.config/gtt/server.yaml`
```yaml
api_key:
  deepl:
    file: /tmp/test.txt
```
`/tmp/test.txt`
```
abcde-fghij-lol
```
results to the same error message
